name: release
on:
  push:
    tags:
      - v*.*.*
jobs:
  publish_binary:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'provider/go.mod'
        cache: true
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.7.1
      with:
        repo: pulumi/pulumictl
    - name: Set PreRelease Version
      run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
    - name: release-notes
      run: make release-notes
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3.1.0
      with:
        args: -p 3 release --rm-dist --release-notes=_out/RELEASE_NOTES.md
        version: latest
